import {v7 as uuid7} from "uuid";

export const consumerSeed = {
    "id": String(`C-${uuid7()}`),
    "name": "Ilham Hakim",
    "email": "ilhamhakim@gmail.com",
    "sex": "Laki-laki",
    "birth": "2003-04-11",
    "phone": "085863190000",
    "height": 173,
    "weight": 70,
    "no_history": true,
    "diabetes": false,
    "hypertension": false,
    "cardiovascular": false,
    "password": "abc12345",
    "password_confirmation": "abc12345"
}

export const restaurantSeed = {
    "id": String(`R-${uuid7()}`),
    "name": "Restoran Karimata",
    "email": "restorankarimata@gmail.com",
    "phone": "085782887745",
    "province": "Jawa Barat",
    "city": "Bogor",
    "address_detail": "Depan Pintu Tol Sentul Selatan-2 The Grand, Jl. Tol Lkr. Luar Bogor",
    "image": "www.example.com",
    "password": "abc12345",
}

const adminSeed = {
    "id": String(`R-${uuid7()}`),
    "email": "admin@gmail.com",
    "password": "abc12345"
}

const menuSeed = [
    {
        "name": "Nasi",
        "category": "Makanan Pokok",
        "portion": 1,
        "price": 8000,
        "status": "Approved",
        "description": "Nasi putih yang disajikan hangat, cocok sebagai pelengkap berbagai hidangan.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 260,
        "weight_with_bdd": 260,
        "calory": 468,
        "protein": 7.8,
        "fat": 0.8,
        "carbohydrate": 103.5,
        "fiber": 0.5,
        "natrium": 2.6,
        "cholesterol": 0,
        "mufa": 0.3,
        "pufa": 0.3,
        "sfa": 0.3
    },
    {
        "name": "Patin Bakar Dalam Bambu",
        "category": "Lauk Pauk",
        "portion": 4,
        "price": 160000,
        "status": "Approved",
        "description": "Ikan patin yang dimasak dengan teknik tradisional dalam bambu, menghasilkan aroma khas.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 865,
        "weight_with_bdd": 486,
        "calory": 1395,
        "protein": 141.5,
        "fat": 82.3,
        "carbohydrate": 17.8,
        "fiber": 1.9,
        "natrium": 1934.37,
        "cholesterol": 330,
        "mufa": 0.6,
        "pufa": 7.6,
        "sfa": 10.8
    },
    {
        "name": "Gurame Bakar Kecap",
        "category": "Lauk Pauk",
        "portion": 3,
        "price": 135000,
        "status": "Approved",
        "description": "Ikan gurame bakar yang dibalut kecap manis, menghasilkan rasa gurih dan manis sempurna.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 398,
        "weight_with_bdd": 252,
        "calory": 644,
        "protein": 88.3,
        "fat": 27.9,
        "carbohydrate": 4.6,
        "fiber": 0,
        "natrium": 880.82,
        "cholesterol": 419.2,
        "mufa": 19.8,
        "pufa": 8.4,
        "sfa": 20.9
    },
    {
        "name": "Patin Goreng Kremes",
        "category": "Lauk Pauk",
        "portion": 4,
        "price": 95000,
        "status": "Approved",
        "description": "Patin yang digoreng renyah dengan tambahan kremes yang gurih dan kriuk.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 868,
        "weight_with_bdd": 486,
        "calory": 2627,
        "protein": 137.5,
        "fat": 215.7,
        "carbohydrate": 31,
        "fiber": 0.5,
        "natrium": 1282.55,
        "cholesterol": 370.44,
        "mufa": 18.8,
        "pufa": 9.8,
        "sfa": 135.1
    },
    {
        "name": "Gurame Goreng Honje",
        "category": "Lauk Pauk",
        "portion": 3,
        "price": 140000,
        "status": "Approved",
        "description": "Gurame goreng dengan cita rasa unik dari bunga kecombrang atau honje.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 787,
        "weight_with_bdd": 641,
        "calory": 2064,
        "protein": 99.3,
        "fat": 70.2,
        "carbohydrate": 123.5,
        "fiber": 10.2,
        "natrium": 1562.44,
        "cholesterol": 392.6,
        "mufa": 21.7,
        "pufa": 9.4,
        "sfa": 59.6
    },
    {
        "name": "Gurame Goreng Asam Manis",
        "category": "Lauk Pauk",
        "portion": 3,
        "price": 135000,
        "status": "Approved",
        "description": "Ikan gurame goreng disajikan dengan saus asam manis yang segar dan lezat.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 951,
        "weight_with_bdd": 805,
        "calory": 1437,
        "protein": 96.7,
        "fat": 79.1,
        "carbohydrate": 81.3,
        "fiber": 2.8,
        "natrium": 1993.74,
        "cholesterol": 392.6,
        "mufa": 22.9,
        "pufa": 9.6,
        "sfa": 68
    },
    {
        "name": "Gurame Goreng Asam Pedas",
        "category": "Lauk Pauk",
        "portion": 3,
        "price": 135000,
        "status": "Approved",
        "description": "Gurame goreng dengan saus asam pedas yang menyegarkan dan menggugah selera.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 951,
        "weight_with_bdd": 805,
        "calory": 1208,
        "protein": 99.5,
        "fat": 70.5,
        "carbohydrate": 39.3,
        "fiber": 16.5,
        "natrium": 1032.15,
        "cholesterol": 392.6,
        "mufa": 24.7,
        "pufa": 18.6,
        "sfa": 63.1
    },
    {
        "name": "Gurame Goreng Kering",
        "category": "Lauk Pauk",
        "portion": 3,
        "price": 135000,
        "status": "Approved",
        "description": "Ikan gurame digoreng hingga kering dan renyah, cocok untuk dinikmati dengan nasi.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 671,
        "weight_with_bdd": 525,
        "calory": 1003,
        "protein": 93.8,
        "fat": 67.8,
        "carbohydrate": 0.2,
        "fiber": 0.1,
        "natrium": 318.82,
        "cholesterol": 392.6,
        "mufa": 21.5,
        "pufa": 9.2,
        "sfa": 59.4
    },
    {
        "name": "Gurame Goreng Rica-Rica",
        "category": "Lauk Pauk",
        "portion": 3,
        "price": 135000,
        "status": "Approved",
        "description": "Ikan gurame goreng yang disajikan dengan sambal rica-rica khas Manado.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 871,
        "weight_with_bdd": 725,
        "calory": 1139,
        "protein": 95.4,
        "fat": 77.2,
        "carbohydrate": 12,
        "fiber": 1.5,
        "natrium": 1582.69,
        "cholesterol": 392.6,
        "mufa": 22.6,
        "pufa": 9.5,
        "sfa": 66.8
    },
    {
        "name": "Udang Bakar Kecap",
        "category": "Lauk Pauk",
        "portion": 2,
        "price": 80000,
        "status": "Approved",
        "description": "Udang segar yang dibakar dengan bumbu kecap, menghasilkan rasa manis gurih.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 173,
        "weight_with_bdd": 103,
        "calory": 181,
        "protein": 22.8,
        "fat": 8.6,
        "carbohydrate": 2.2,
        "fiber": 0,
        "natrium": 503.08,
        "cholesterol": 254.7,
        "mufa": 2.6,
        "pufa": 0.8,
        "sfa": 5.3
    },
    {
        "name": "Udang Bakar Madu",
        "category": "Lauk Pauk",
        "portion": 2,
        "price": 80000,
        "status": "Approved",
        "description": "Udang bakar dengan lapisan madu yang manis dan legit, sempurna untuk pecinta seafood.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 173,
        "weight_with_bdd": 103,
        "calory": 232,
        "protein": 21.5,
        "fat": 8.3,
        "carbohydrate": 18.4,
        "fiber": 0,
        "natrium": 248.24,
        "cholesterol": 254.7,
        "mufa": 2.6,
        "pufa": 0.8,
        "sfa": 5.3
    },
    {
        "name": "Udang Goreng Tepung",
        "category": "Lauk Pauk",
        "portion": 2,
        "price": 60000,
        "status": "Approved",
        "description": "Udang yang dibalut tepung renyah dan digoreng hingga kuning keemasan.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 143,
        "weight_with_bdd": 143,
        "calory": 237,
        "protein": 14.1,
        "fat": 5.4,
        "carbohydrate": 32.8,
        "fiber": 0.3,
        "natrium": 389.3,
        "cholesterol": 149.52,
        "mufa": 0.9,
        "pufa": 0.5,
        "sfa": 4.4
    },
    {
        "name": "Udang Saus Asam Pedas",
        "category": "Lauk Pauk",
        "portion": 2,
        "price": 60000,
        "status": "Approved",
        "description": "Udang goreng disajikan dengan saus asam pedas yang memberikan sensasi segar dan pedas.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 150,
        "weight_with_bdd": 150,
        "calory": 141,
        "protein": 13.9,
        "fat": 5.4,
        "carbohydrate": 8.5,
        "fiber": 3.5,
        "natrium": 260.78,
        "cholesterol": 138,
        "mufa": 1.5,
        "pufa": 2.4,
        "sfa": 5.1
    },
    {
        "name": "Udang Saus Asam Manis",
        "category": "Lauk Pauk",
        "portion": 2,
        "price": 60000,
        "status": "Approved",
        "description": "Udang goreng dengan saus asam manis yang menyatu dengan gurihnya udang.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 156,
        "weight_with_bdd": 156,
        "calory": 170,
        "protein": 13.4,
        "fat": 8.5,
        "carbohydrate": 9.7,
        "fiber": 0.7,
        "natrium": 593.78,
        "cholesterol": 138,
        "mufa": 1.2,
        "pufa": 0.5,
        "sfa": 7.2
    },
    {
        "name": "Cumi Bakar Kecap",
        "category": "Lauk Pauk",
        "portion": 2,
        "price": 80000,
        "status": "Approved",
        "description": "Cumi bakar dengan bumbu kecap yang manis dan gurih, menghasilkan rasa lezat dan aroma yang khas.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 75,
        "weight_with_bdd": 75,
        "calory": 123,
        "protein": 8.8,
        "fat": 8.7,
        "carbohydrate": 2.2,
        "fiber": 0,
        "natrium": 338.7,
        "cholesterol": 213.2,
        "mufa": 2.4,
        "pufa": 0.7,
        "sfa": 5.3
    },
    {
        "name": "Cumi Bakar Sambal Ijo",
        "category": "Lauk Pauk",
        "portion": 2,
        "price": 80000,
        "status": "Approved",
        "description": "Cumi bakar dengan sambal hijau yang pedas segar, cocok untuk pecinta pedas.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 110,
        "weight_with_bdd": 110,
        "calory": 102,
        "protein": 8.5,
        "fat": 4.5,
        "carbohydrate": 6.7,
        "fiber": 1.3,
        "natrium": 262.01,
        "cholesterol": 194,
        "mufa": 0.6,
        "pufa": 0.5,
        "sfa": 3.7
    },
    {
        "name": "Cumi Goreng Tepung",
        "category": "Lauk Pauk",
        "portion": 2,
        "price": 60000,
        "status": "Approved",
        "description": "Cumi goreng dengan tepung crispy yang renyah, nikmat disantap dengan saus cocol.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 120,
        "weight_with_bdd": 120,
        "calory": 163,
        "protein": 8.8,
        "fat": 3.5,
        "carbohydrate": 24,
        "fiber": 0.2,
        "natrium": 233.66,
        "cholesterol": 205.2,
        "mufa": 0.5,
        "pufa": 0.5,
        "sfa": 2.8
    },
    {
        "name": "Cumi Balado Pete",
        "category": "Lauk Pauk",
        "portion": 2,
        "price": 60000,
        "status": "Approved",
        "description": "Cumi dimasak dengan sambal balado dan pete, menghasilkan rasa pedas yang unik.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 305,
        "weight_with_bdd": 305,
        "calory": 262,
        "protein": 22.4,
        "fat": 12.5,
        "carbohydrate": 14.8,
        "fiber": 2,
        "natrium": 489.94,
        "cholesterol": 447.6,
        "mufa": 3.4,
        "pufa": 2,
        "sfa": 22.1
    },
    {
        "name": "Cumi Goreng Rica-Rica",
        "category": "Lauk Pauk",
        "portion": 2,
        "price": 60000,
        "status": "Approved",
        "description": "Cumi goreng disajikan dengan sambal rica-rica yang pedas dan lezat.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 137,
        "weight_with_bdd": 137,
        "calory": 115,
        "protein": 8.1,
        "fat": 6.9,
        "carbohydrate": 4.9,
        "fiber": 0.6,
        "natrium": 541.69,
        "cholesterol": 240.48,
        "mufa": 0.9,
        "pufa": 0.7,
        "sfa": 3.1
    },
    {
        "name": "Dori Crispy",
        "category": "Lauk Pauk",
        "portion": 2,
        "price": 75000,
        "status": "Approved",
        "description": "Ikan dori yang digoreng hingga crispy, nikmat dan ringan di lidah.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 172,
        "weight_with_bdd": 172,
        "calory": 325,
        "protein": 18.1,
        "fat": 22.5,
        "carbohydrate": 14.1,
        "fiber": 0.1,
        "natrium": 242.53,
        "cholesterol": 61.53,
        "mufa": 2.9,
        "pufa": 1.2,
        "sfa": 13.6
    },
    {
        "name": "Dori Crispy Mayonaise",
        "category": "Lauk Pauk",
        "portion": 2,
        "price": 750000,
        "status": "Approved",
        "description": "Dori goreng yang disajikan dengan saus mayonaise creamy yang lezat.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 182,
        "weight_with_bdd": 182,
        "calory": 449,
        "protein": 17.5,
        "fat": 36.3,
        "carbohydrate": 12.8,
        "fiber": 0,
        "natrium": 314.87,
        "cholesterol": 103.77,
        "mufa": 9,
        "pufa": 16.9,
        "sfa": 16.9
    },
    {
        "name": "Ayam Bakar Kecap",
        "category": "Lauk Pauk",
        "portion": 1,
        "price": 250000,
        "status": "Approved",
        "description": "Ayam bakar yang dibumbui kecap manis, menghasilkan cita rasa manis dan gurih.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 132,
        "weight_with_bdd": 132,
        "calory": 311,
        "protein": 12.8,
        "fat": 28,
        "carbohydrate": 2.3,
        "fiber": 0,
        "natrium": 444.1,
        "cholesterol": 115.5,
        "mufa": 11.2,
        "pufa": 4.9,
        "sfa": 13
    },
    {
        "name": "Ayam Bakar Sambal Ijo",
        "category": "Lauk Pauk",
        "portion": 1,
        "price": 25000,
        "status": "Approved",
        "description": "Ayam bakar dengan sambal hijau yang pedas segar, cocok dinikmati dengan nasi hangat.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 198,
        "weight_with_bdd": 198,
        "calory": 324,
        "protein": 12.3,
        "fat": 27.7,
        "carbohydrate": 6.7,
        "fiber": 1.3,
        "natrium": 373.12,
        "cholesterol": 84.5,
        "mufa": 9.3,
        "pufa": 4.8,
        "sfa": 15.5
    },
    {
        "name": "Ayam Goreng Kering",
        "category": "Lauk Pauk",
        "portion": 1,
        "price": 25000,
        "status": "Approved",
        "description": "Ayam yang digoreng hingga kering dan renyah, disajikan dengan sambal khas.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 118,
        "weight_with_bdd": 118,
        "calory": 281,
        "protein": 11.3,
        "fat": 26.3,
        "carbohydrate": 0.1,
        "fiber": 0,
        "natrium": 128.29,
        "cholesterol": 84.5,
        "mufa": 9,
        "pufa": 4.7,
        "sfa": 14.5
    },
    {
        "name": "Ayam Goreng Rica-Rica",
        "category": "Lauk Pauk",
        "portion": 1,
        "price": 25000,
        "status": "Approved",
        "description": "Ayam goreng yang disajikan dengan sambal rica-rica pedas khas Manado.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 168,
        "weight_with_bdd": 168,
        "calory": 315,
        "protein": 11.7,
        "fat": 28.6,
        "carbohydrate": 3,
        "fiber": 0.3,
        "natrium": 413.97,
        "cholesterol": 84.5,
        "mufa": 9.3,
        "pufa": 4.8,
        "sfa": 16.3
    },
    {
        "name": "Ayam Goreng Kremes",
        "category": "Lauk Pauk",
        "portion": 1,
        "price": 25000,
        "status": "Approved",
        "description": "Ayam goreng yang disajikan dengan kremes renyah di atasnya.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 143,
        "weight_with_bdd": 143,
        "calory": 339,
        "protein": 12.7,
        "fat": 27.2,
        "carbohydrate": 11.7,
        "fiber": 0.1,
        "natrium": 267.59,
        "cholesterol": 102.76,
        "mufa": 9.3,
        "pufa": 4.8,
        "sfa": 14.9
    },
    {
        "name": "Sup Buntut Sapi",
        "category": "Lauk Pauk",
        "portion": 1,
        "price": 80000,
        "status": "Approved",
        "description": "Sup hangat dengan potongan buntut sapi yang lembut, disajikan dengan kuah bening.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 195,
        "weight_with_bdd": 195,
        "calory": 160,
        "protein": 12.6,
        "fat": 8.8,
        "carbohydrate": 6.7,
        "fiber": 0.6,
        "natrium": 418.64,
        "cholesterol": 45.34,
        "mufa": 4.8,
        "pufa": 0.8,
        "sfa": 5.2
    },
    {
        "name": "Sup Gurame Pedas Kemangi",
        "category": "Lauk Pauk",
        "portion": 3,
        "price": 135000,
        "status": "Approved",
        "description": "Sup gurame dengan kuah pedas yang harum daun kemangi, menyegarkan dan nikmat.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 786,
        "weight_with_bdd": 640,
        "calory": 444,
        "protein": 94.1,
        "fat": 3.6,
        "carbohydrate": 2.1,
        "fiber": 0.2,
        "natrium": 423.35,
        "cholesterol": 392.6,
        "mufa": 14.1,
        "pufa": 8.2,
        "sfa": 6.4
    },
    {
        "name": "Sup Gurame Asam Kemangi",
        "category": "Lauk Pauk",
        "portion": 3,
        "price": 135000,
        "status": "Approved",
        "description": "Sup gurame dengan kuah asam dan daun kemangi, cocok untuk penyuka rasa asam segar.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 781,
        "weight_with_bdd": 635,
        "calory": 434,
        "protein": 93.8,
        "fat": 3.3,
        "carbohydrate": 0.6,
        "fiber": 0.1,
        "natrium": 444.31,
        "cholesterol": 392.6,
        "mufa": 14.1,
        "pufa": 8.2,
        "sfa": 6.4
    },
    {
        "name": "Sup Gurame Kuah Kuning",
        "category": "Lauk Pauk",
        "portion": 3,
        "price": 135000,
        "status": "Approved",
        "description": "Sup gurame dengan kuah kuning yang kaya rempah, memberikan rasa hangat dan gurih.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 820,
        "weight_with_bdd": 674,
        "calory": 466,
        "protein": 94.8,
        "fat": 5.9,
        "carbohydrate": 1.8,
        "fiber": 0.2,
        "natrium": 495.6,
        "cholesterol": 392.6,
        "mufa": 14.2,
        "pufa": 8.3,
        "sfa": 6.5
    },
    {
        "name": "Sup Ayam + Sayur",
        "category": "Lauk Pauk",
        "portion": 2,
        "price": 25000,
        "status": "Approved",
        "description": "Sup ayam dengan sayuran segar, cocok sebagai sajian sehat dan lezat.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 679,
        "weight_with_bdd": 679,
        "calory": 209,
        "protein": 12.4,
        "fat": 15.8,
        "carbohydrate": 4.8,
        "fiber": 0.9,
        "natrium": 708.11,
        "cholesterol": 84.5,
        "mufa": 7.7,
        "pufa": 4.6,
        "sfa": 5.5
    },
    {
        "name": "Sup Ayam Pedas Kemangi",
        "category": "Lauk Pauk",
        "portion": 2,
        "price": 25000,
        "status": "Approved",
        "description": "Sup ayam dengan kuah pedas dan aroma segar daun kemangi yang menggugah selera.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 302,
        "weight_with_bdd": 302,
        "calory": 198,
        "protein": 11.6,
        "fat": 15.9,
        "carbohydrate": 2.1,
        "fiber": 0.2,
        "natrium": 343.35,
        "cholesterol": 84.5,
        "mufa": 7.7,
        "pufa": 4.5,
        "sfa": 5.5
    },
    {
        "name": "Sup Ayam Asam Kemangi",
        "category": "Lauk Pauk",
        "portion": 2,
        "price": 25000,
        "status": "Approved",
        "description": "Sup ayam dengan cita rasa asam dan harum daun kemangi, menyegarkan dan gurih.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 302,
        "weight_with_bdd": 302,
        "calory": 188,
        "protein": 11.4,
        "fat": 15.6,
        "carbohydrate": 0.6,
        "fiber": 0.1,
        "natrium": 371.38,
        "cholesterol": 84.5,
        "mufa": 7.7,
        "pufa": 4.5,
        "sfa": 5.5
    },
    {
        "name": "Sup Ayam Kuah Kuning",
        "category": "Lauk Pauk",
        "portion": 2,
        "price": 25000,
        "status": "Approved",
        "description": "Sup ayam dengan kuah kuning berempah, lezat dan menghangatkan.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 307,
        "weight_with_bdd": 307,
        "calory": 215,
        "protein": 12.1,
        "fat": 17.8,
        "carbohydrate": 1.5,
        "fiber": 0.2,
        "natrium": 370.34,
        "cholesterol": 84.5,
        "mufa": 7.8,
        "pufa": 4.6,
        "sfa": 5.6
    },
    {
        "name": "Sayur Asem",
        "category": "Sayuran",
        "portion": 4,
        "price": 12000,
        "status": "Approved",
        "description": "Sayur asem yang segar dengan kuah asam dari bumbu tradisional khas Indonesia.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 1340,
        "weight_with_bdd": 1340,
        "calory": 1255,
        "protein": 49.3,
        "fat": 53.1,
        "carbohydrate": 172,
        "fiber": 31.3,
        "natrium": 1479.56,
        "cholesterol": 10.8,
        "mufa": 25.9,
        "pufa": 14.6,
        "sfa": 6.7
    },
    {
        "name": "Cah Kangkung Polos",
        "category": "Sayuran",
        "portion": 3,
        "price": 20000,
        "status": "Approved",
        "description": "Tumis kangkung sederhana dengan rasa gurih dan segar.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 137,
        "weight_with_bdd": 137,
        "calory": 176,
        "protein": 20.7,
        "fat": 12.6,
        "carbohydrate": 3.3,
        "fiber": 1.7,
        "natrium": 1151.21,
        "cholesterol": 8,
        "mufa": 1.4,
        "pufa": 0.3,
        "sfa": 8.2
    },
    {
        "name": "Cah Kangkung Terasi",
        "category": "Sayuran",
        "portion": 3,
        "price": 20000,
        "status": "Approved",
        "description": "Tumis kangkung dengan bumbu terasi yang harum dan menggugah selera.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 137,
        "weight_with_bdd": 137,
        "calory": 181,
        "protein": 21.4,
        "fat": 2.7,
        "carbohydrate": 3.6,
        "fiber": 1.7,
        "natrium": 1175.96,
        "cholesterol": 2.2,
        "mufa": 1.4,
        "pufa": 0.3,
        "sfa": 8.2
    },
    {
        "name": "Cah Kangkung Tauco",
        "category": "Sayuran",
        "portion": 3,
        "price": 20000,
        "status": "Approved",
        "description": "Kangkung yang dimasak dengan saus tauco, memberikan rasa gurih dan sedikit asin.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 137,
        "weight_with_bdd": 137,
        "calory": 180,
        "protein": 20.9,
        "fat": 12.7,
        "carbohydrate": 3.7,
        "fiber": 1.7,
        "natrium": 799.36,
        "cholesterol": 0,
        "mufa": 1.4,
        "pufa": 0.4,
        "sfa": 8.3
    },
    {
        "name": "Tauge Cah Polos",
        "category": "Sayuran",
        "portion": 3,
        "price": 15000,
        "status": "Approved",
        "description": "Tauge yang ditumis dengan bumbu ringan, cocok sebagai pelengkap makan.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 137,
        "weight_with_bdd": 137,
        "calory": 151,
        "protein": 5.3,
        "fat": 10.7,
        "carbohydrate": 6.9,
        "fiber": 2.1,
        "natrium": 1143.95,
        "cholesterol": 0,
        "mufa": 2.2,
        "pufa": 2.5,
        "sfa": 8.8
    },
    {
        "name": "Karedok",
        "category": "Sayuran",
        "portion": 3,
        "price": 20000,
        "status": "Approved",
        "description": "Salad khas Sunda yang terdiri dari sayuran segar dan bumbu kacang.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 325,
        "weight_with_bdd": 325,
        "calory": 870,
        "protein": 28.4,
        "fat": 60.5,
        "carbohydrate": 63.2,
        "fiber": 6.8,
        "natrium": 1108.05,
        "cholesterol": 15.6,
        "mufa": 16.5,
        "pufa": 10.1,
        "sfa": 26.4
    },
    {
        "name": "Gado-Gado",
        "category": "Sayuran",
        "portion": 3,
        "price": 20000,
        "status": "Approved",
        "description": "Hidangan khas Indonesia berupa sayuran rebus dengan bumbu kacang yang kental.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 333,
        "weight_with_bdd": 333,
        "calory": 430,
        "protein": 22.4,
        "fat": 23.5,
        "carbohydrate": 35.3,
        "fiber": 3.6,
        "natrium": 1214.71,
        "cholesterol": 233.2,
        "mufa": 4.9,
        "pufa": 2.6,
        "sfa": 14.6
    },
    {
        "name": "Tauge Cah Ikan Asin",
        "category": "Sayuran",
        "portion": 3,
        "price": 25000,
        "status": "Approved",
        "description": "Tauge yang ditumis dengan ikan asin, memberikan perpaduan rasa gurih dan segar.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 147,
        "weight_with_bdd": 147,
        "calory": 202,
        "protein": 6.6,
        "fat": 15.8,
        "carbohydrate": 7.1,
        "fiber": 2.1,
        "natrium": 1294,
        "cholesterol": 2.5,
        "mufa": 2.9,
        "pufa": 3,
        "sfa": 13
    },
    {
        "name": "Oseng-Oseng Pakcoy",
        "category": "Sayuran",
        "portion": 3,
        "price": 25000,
        "status": "Approved",
        "description": "Tumis pakcoy segar dengan bumbu sederhana, nikmat sebagai lauk sehat.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 155,
        "weight_with_bdd": 155,
        "calory": 214,
        "protein": 1.7,
        "fat": 15.3,
        "carbohydrate": 16.9,
        "fiber": 2.9,
        "natrium": 1157.86,
        "cholesterol": 2.2,
        "mufa": 1.4,
        "pufa": 0.3,
        "sfa": 8.2
    },
    {
        "name": "Brokoli Bawang Putih",
        "category": "Sayuran",
        "portion": 3,
        "price": 25000,
        "status": "Approved",
        "description": "Brokoli yang ditumis dengan bawang putih, memberikan rasa segar dan gurih.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 145,
        "weight_with_bdd": 145,
        "calory": 212,
        "protein": 4.6,
        "fat": 10.6,
        "carbohydrate": 25.1,
        "fiber": 4.2,
        "natrium": 1143.36,
        "cholesterol": 0,
        "mufa": 1.2,
        "pufa": 0.4,
        "sfa": 8.3
    },
    {
        "name": "Selada Tahu Telur",
        "category": "Sayuran",
        "portion": 4,
        "price": 40000,
        "status": "Approved",
        "description": "Salad dengan tahu dan telur yang digoreng, disajikan dengan saus kacang.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 942,
        "weight_with_bdd": 942,
        "calory": 481,
        "protein": 16.8,
        "fat": 19.5,
        "carbohydrate": 42.9,
        "fiber": 2.9,
        "natrium": 1637.27,
        "cholesterol": 233.2,
        "mufa": 4.8,
        "pufa": 3.4,
        "sfa": 11
    },
    {
        "name": "Pakcoy Udang Rebon",
        "category": "Sayuran",
        "portion": 3,
        "price": 30000,
        "status": "Approved",
        "description": "Tumis pakcoy dengan udang rebon, menghasilkan rasa gurih dan segar.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 160,
        "weight_with_bdd": 160,
        "calory": 172,
        "protein": 4.1,
        "fat": 10.5,
        "carbohydrate": 14.5,
        "fiber": 2.6,
        "natrium": 1183.21,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Sup Tahu Tauge",
        "category": "Sayuran",
        "portion": 3,
        "price": 25000,
        "status": "Approved",
        "description": "Sup sederhana dengan tahu dan tauge yang segar, cocok untuk sajian ringan.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 895,
        "weight_with_bdd": 895,
        "calory": 456,
        "protein": 34.1,
        "fat": 31.1,
        "carbohydrate": 13.8,
        "fiber": 2.5,
        "natrium": 1421.81,
        "cholesterol": 26.9,
        "mufa": 8.1,
        "pufa": 10.2,
        "sfa": 17.2
    },
    {
        "name": "Sup Tahu + Sayuran",
        "category": "Sayuran",
        "portion": 3,
        "price": 25000,
        "status": "Approved",
        "description": "Sup tahu yang disajikan dengan sayuran segar, menghasilkan rasa yang gurih dan sehat.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 940,
        "weight_with_bdd": 940,
        "calory": 471,
        "protein": 32.2,
        "fat": 31.9,
        "carbohydrate": 18.8,
        "fiber": 3.2,
        "natrium": 1242.71,
        "cholesterol": 20.7,
        "mufa": 6.7,
        "pufa": 8.5,
        "sfa": 15.3
    },
    {
        "name": "Sup Sayuran",
        "category": "Sayuran",
        "portion": 3,
        "price": 20000,
        "status": "Approved",
        "description": "Sup berisi aneka sayuran segar yang cocok dinikmati sebagai makanan sehat dan ringan.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 915,
        "weight_with_bdd": 915,
        "calory": 323,
        "protein": 5.5,
        "fat": 20.6,
        "carbohydrate": 30,
        "fiber": 4.7,
        "natrium": 1452.76,
        "cholesterol": 20.7,
        "mufa": 3.8,
        "pufa": 1.6,
        "sfa": 13.5
    },
    {
        "name": "Terong Ikan Asin",
        "category": "Sayuran",
        "portion": 3,
        "price": 30000,
        "status": "Approved",
        "description": "Terong yang dimasak dengan ikan asin, menghasilkan kombinasi rasa gurih dan pedas.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 205,
        "weight_with_bdd": 205,
        "calory": 178,
        "protein": 6.7,
        "fat": 10.6,
        "carbohydrate": 12.2,
        "fiber": 3.7,
        "natrium": 1438.38,
        "cholesterol": 7.5,
        "mufa": 1.7,
        "pufa": 1.3,
        "sfa": 8.5
    },
    {
        "name": "Terong Sambal Hijau",
        "category": "Sayuran",
        "portion": 3,
        "price": 25000,
        "status": "Approved",
        "description": "Terong yang digoreng dan disajikan dengan sambal hijau pedas dan segar.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 300,
        "weight_with_bdd": 300,
        "calory": 298,
        "protein": 3.4,
        "fat": 23,
        "carbohydrate": 20.5,
        "fiber": 5.6,
        "natrium": 459.05,
        "cholesterol": 0,
        "mufa": 2.7,
        "pufa": 0.6,
        "sfa": 18.2
    },
    {
        "name": "Terong Penyet",
        "category": "Sayuran",
        "portion": 3,
        "price": 25000,
        "status": "Approved",
        "description": "Terong yang digoreng dan dipenyet dengan sambal pedas, menggugah selera makan.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 300,
        "weight_with_bdd": 300,
        "calory": 284,
        "protein": 3.6,
        "fat": 21.7,
        "carbohydrate": 19.8,
        "fiber": 4.6,
        "natrium": 440.59,
        "cholesterol": 0,
        "mufa": 2.5,
        "pufa": 0.6,
        "sfa": 17.2
    },
    {
        "name": "Lumpia",
        "category": "Snack",
        "portion": 2,
        "price": 20000,
        "status": "Approved",
        "description": "Lumpia goreng berisi sayuran dan daging cincang, renyah di luar, lembut di dalam.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 132,
        "weight_with_bdd": 0,
        "calory": 275,
        "protein": 4.6,
        "fat": 21.2,
        "carbohydrate": 17.2,
        "fiber": 0.5,
        "natrium": 323.41,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Tahu + Tempe Goreng",
        "category": "Snack",
        "portion": 2,
        "price": 15000,
        "status": "Approved",
        "description": "Tahu dan tempe yang digoreng hingga renyah, cocok sebagai camilan atau lauk.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 150,
        "weight_with_bdd": 0,
        "calory": 368,
        "protein": 19,
        "fat": 28,
        "carbohydrate": 14.7,
        "fiber": 0.9,
        "natrium": 162.72,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jamur Crispy",
        "category": "Snack",
        "portion": 2,
        "price": 15000,
        "status": "Approved",
        "description": "Jamur yang digoreng hingga renyah, nikmat disantap dengan saus cocol.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 125,
        "weight_with_bdd": 0,
        "calory": 236,
        "protein": 2.3,
        "fat": 8.2,
        "carbohydrate": 38.6,
        "fiber": 2.9,
        "natrium": 361.35,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Tahu Kresz",
        "category": "Snack",
        "portion": 2,
        "price": 25000,
        "status": "Approved",
        "description": "Tahu goreng yang renyah di luar, lembut di dalam, cocok sebagai camilan gurih.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 150,
        "weight_with_bdd": 0,
        "calory": 340,
        "protein": 16.7,
        "fat": 29.5,
        "carbohydrate": 6.3,
        "fiber": 0.2,
        "natrium": 129.38,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Buah Naga",
        "category": "Minuman",
        "portion": 1,
        "price": 25000,
        "status": "Approved",
        "description": "Jus buah naga segar yang kaya akan vitamin dan antioksidan, menyegarkan tubuh.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 267,
        "protein": 1.4,
        "fat": 2.5,
        "carbohydrate": 57.4,
        "fiber": 2.6,
        "natrium": 8.57,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Sunset",
        "category": "Minuman",
        "portion": 1,
        "price": 25000,
        "status": "Approved",
        "description": "Jus campuran buah tropis yang menyegarkan, dengan warna cantik seperti matahari terbenam.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 341,
        "protein": 1,
        "fat": 0.3,
        "carbohydrate": 83.8,
        "fiber": 2.1,
        "natrium": 9.74,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Stamina",
        "category": "Minuman",
        "portion": 1,
        "price": 30000,
        "status": "Approved",
        "description": "Jus campuran buah-buahan kaya energi untuk meningkatkan stamina tubuh.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 282,
        "protein": 7.7,
        "fat": 9.6,
        "carbohydrate": 42.4,
        "fiber": 0.3,
        "natrium": 78.31,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Munser",
        "category": "Minuman",
        "portion": 1,
        "price": 25000,
        "status": "Approved",
        "description": "Jus segar dengan perpaduan buah-buahan tropis untuk sensasi rasa manis dan segar.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 212,
        "protein": 0.7,
        "fat": 0.4,
        "carbohydrate": 50.8,
        "fiber": 0.7,
        "natrium": 6.05,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Munas",
        "category": "Minuman",
        "portion": 1,
        "price": 25000,
        "status": "Approved",
        "description": "Jus buah campuran yang segar dengan rasa manis yang pas.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 233,
        "protein": 0.7,
        "fat": 0.4,
        "carbohydrate": 56.3,
        "fiber": 0.6,
        "natrium": 12.61,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Tensiless",
        "category": "Minuman",
        "portion": 1,
        "price": 25000,
        "status": "Approved",
        "description": "Jus buah khusus untuk membantu menurunkan tekanan darah, segar dan sehat.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 240,
        "protein": 0.9,
        "fat": 0.4,
        "carbohydrate": 59.2,
        "fiber": 1.9,
        "natrium": 8.31,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Glucoless",
        "category": "Minuman",
        "portion": 1,
        "price": 25000,
        "status": "Approved",
        "description": "Jus dengan campuran buah-buahan yang membantu menjaga kadar gula darah.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 255,
        "protein": 1.3,
        "fat": 0.5,
        "carbohydrate": 62.6,
        "fiber": 1.9,
        "natrium": 32.33,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Choleles",
        "category": "Minuman",
        "portion": 1,
        "price": 25000,
        "status": "Approved",
        "description": "Jus buah yang membantu menjaga kadar kolesterol, cocok untuk diet sehat.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 243,
        "protein": 0.6,
        "fat": 0.2,
        "carbohydrate": 60.5,
        "fiber": 1.1,
        "natrium": 6.85,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Jeruk",
        "category": "Minuman",
        "portion": 1,
        "price": 25000,
        "status": "Approved",
        "description": "Jus jeruk segar yang kaya akan vitamin C, cocok untuk menyegarkan tubuh.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 308,
        "protein": 0.9,
        "fat": 0.2,
        "carbohydrate": 73.9,
        "fiber": 1.4,
        "natrium": 4.67,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Nanas",
        "category": "Minuman",
        "portion": 1,
        "price": 20000,
        "status": "Approved",
        "description": "Jus nanas segar dengan cita rasa asam manis yang menyegarkan.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 284,
        "protein": 0.3,
        "fat": 0.2,
        "carbohydrate": 67.9,
        "fiber": 0.3,
        "natrium": 10.21,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Wortel",
        "category": "Minuman",
        "portion": 1,
        "price": 20000,
        "status": "Approved",
        "description": "Jus wortel yang kaya akan vitamin A, baik untuk kesehatan mata dan kulit.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 291,
        "protein": 0.8,
        "fat": 0.5,
        "carbohydrate": 69,
        "fiber": 0.8,
        "natrium": 56.67,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Melon",
        "category": "Minuman",
        "portion": 1,
        "price": 20000,
        "status": "Approved",
        "description": "Jus melon segar yang manis dan kaya air, cocok untuk melepas dahaga.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 242,
        "protein": 0.5,
        "fat": 0.3,
        "carbohydrate": 56.9,
        "fiber": 0.9,
        "natrium": 24.02,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Semangka",
        "category": "Minuman",
        "portion": 1,
        "price": 20000,
        "status": "Approved",
        "description": "Jus semangka segar yang kaya air, cocok untuk menyegarkan tubuh di hari panas.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 236,
        "protein": 0.5,
        "fat": 0.2,
        "carbohydrate": 56.5,
        "fiber": 0.4,
        "natrium": 6.97,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Strawberry",
        "category": "Minuman",
        "portion": 1,
        "price": 25000,
        "status": "Approved",
        "description": "Jus strawberry dengan rasa manis asam yang segar, cocok sebagai minuman penutup.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 242,
        "protein": 0.7,
        "fat": 0.3,
        "carbohydrate": 57.8,
        "fiber": 2,
        "natrium": 1.53,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Pepaya",
        "category": "Minuman",
        "portion": 1,
        "price": 20000,
        "status": "Approved",
        "description": "Jus pepaya segar yang kaya serat, baik untuk pencernaan dan menyegarkan.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 140,
        "protein": 0.4,
        "fat": 0.1,
        "carbohydrate": 34.2,
        "fiber": 1.2,
        "natrium": 3.27,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Tomat",
        "category": "Minuman",
        "portion": 1,
        "price": 20000,
        "status": "Approved",
        "description": "Jus tomat segar yang kaya akan vitamin C dan antioksidan, baik untuk kesehatan.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 287,
        "protein": 1.3,
        "fat": 0.5,
        "carbohydrate": 67.4,
        "fiber": 1.5,
        "natrium": 10.67,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Alpukat",
        "category": "Minuman",
        "portion": 1,
        "price": 25000,
        "status": "Approved",
        "description": "Jus alpukat creamy yang lezat dan kaya nutrisi, cocok untuk camilan sehat.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 234,
        "protein": 0.9,
        "fat": 5.4,
        "carbohydrate": 44.7,
        "fiber": 0.4,
        "natrium": 19.65,
        "cholesterol": 0,
        "mufa": 2.4,
        "pufa": 0.5,
        "sfa": 0.6
    },
    {
        "name": "Jus Sirsak",
        "category": "Minuman",
        "portion": 1,
        "price": 25000,
        "status": "Approved",
        "description": "Jus sirsak yang segar dengan cita rasa manis asam, cocok untuk minuman dingin.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 254,
        "protein": 0.7,
        "fat": 0.2,
        "carbohydrate": 61.2,
        "fiber": 2.2,
        "natrium": 1.89,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Jambu Biji Merah",
        "category": "Minuman",
        "portion": 1,
        "price": 25000,
        "status": "Approved",
        "description": "Jus jambu biji merah segar yang kaya akan vitamin C, menyegarkan dan sehat.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 303,
        "protein": 0.7,
        "fat": 0.2,
        "carbohydrate": 72.7,
        "fiber": 2,
        "natrium": 8.87,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Mangga",
        "category": "Minuman",
        "portion": 1,
        "price": 25000,
        "status": "Approved",
        "description": "Jus mangga segar dengan rasa manis dan asam yang pas, cocok sebagai minuman penutup.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 139,
        "protein": 0.5,
        "fat": 0,
        "carbohydrate": 33.1,
        "fiber": 1,
        "natrium": 2.22,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Es Lemon",
        "category": "Minuman",
        "portion": 1,
        "price": 20000,
        "status": "Approved",
        "description": "Minuman segar dengan perasan lemon yang asam manis, cocok untuk menyegarkan hari.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 281,
        "protein": 0.3,
        "fat": 0.4,
        "carbohydrate": 66,
        "fiber": 0.1,
        "natrium": 17.2,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Jus Blimbing",
        "category": "Minuman",
        "portion": 1,
        "price": 25000,
        "status": "Approved",
        "description": "Jus belimbing segar dengan rasa asam manis yang khas.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 241,
        "protein": 0.3,
        "fat": 0.3,
        "carbohydrate": 57.7,
        "fiber": 2.8,
        "natrium": 3.97,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Es Kelapa Jeruk Peras",
        "category": "Minuman",
        "portion": 1,
        "price": 35000,
        "status": "Approved",
        "description": "Minuman segar dari campuran air kelapa muda dan perasan jeruk, menyegarkan dan kaya elektrolit.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 198,
        "protein": 1.1,
        "fat": 0.6,
        "carbohydrate": 46.3,
        "fiber": 0.7,
        "natrium": 12.37,
        "cholesterol": 0,
        "mufa": 0.1,
        "pufa": 0,
        "sfa": 3.2
    },
    {
        "name": "Es Campuran",
        "category": "Minuman",
        "portion": 1,
        "price": 35000,
        "status": "Approved",
        "description": "Minuman es campur dengan berbagai campuran buah dan bahan-bahan manis lainnya.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 319,
        "protein": 3.3,
        "fat": 11.8,
        "carbohydrate": 66.4,
        "fiber": 2,
        "natrium": 48.03,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Teh Manis",
        "category": "Minuman",
        "portion": 1,
        "price": 7000,
        "status": "Approved",
        "description": "Teh manis yang disajikan hangat atau dingin, cocok sebagai minuman penutup santai.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 263,
        "protein": 0,
        "fat": 0,
        "carbohydrate": 62.7,
        "fiber": 0,
        "natrium": 0.67,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    },
    {
        "name": "Es Cendol",
        "category": "Minuman",
        "portion": 1,
        "price": 35000,
        "status": "Approved",
        "description": "Minuman tradisional dengan cendol, santan, dan gula merah yang manis dan segar.",
        "image_url": "https://i.ibb.co.com/8XmgR4s/2201-i309-032-S-m012-c13-Thai-cuisine-food-flat-composition-2.jpg",
        "weight_per_portion": 0,
        "weight_with_bdd": 0,
        "calory": 368,
        "protein": 3,
        "fat": 10.8,
        "carbohydrate": 64.6,
        "fiber": 1.6,
        "natrium": 27.1,
        "cholesterol": 0,
        "mufa": 0,
        "pufa": 0,
        "sfa": 0
    }
]

