import { ResponseError } from '../error/response-error';
import { prismaClient } from './database';
import { NextFunction, Request, Response } from 'express';

export async function SeedMasterBahanBumbu(
  req: Request,
  res: Response,
  next: NextFunction
) {
  if (process.env.NODE_ENV !== 'development') {
    return next(
      new ResponseError(
        403,
        'Seed Master Bahan and Master Bumbu endpoint is only available in development mode.'
      )
    );
  }

  try {
    const typeData = [
      { name: 'Utama' },
      { name: 'Pelengkap' },
      { name: 'Dasar' },
    ];

    for (const type of typeData) {
      await prismaClient.masterBahanType.upsert({
        where: { name: type.name },
        update: {},
        create: { name: type.name },
      });
    }

    const types = await prismaClient.masterBahanType.findMany();
    const typeMap = new Map(
      types.map((type) => [type.name.toLowerCase(), type.id])
    );

    const masterBahanData = [
      {
        name: 'Ikan patin segar',
        type_id: typeMap.get('utama') || 1,
        bdd: 80,
        calory: 132,
        protein: 17,
        fat: 6.6,
        carbohydrate: 0,
        fiber: 0,
        natrium: 77,
        cholesterol: 73,
        mufa: 3.48,
        pufa: 1.75,
        sfa: 1.76,
      },
      {
        name: 'Kecap',
        type_id: typeMap.get('dasar') || 3,
        bdd: 100,
        calory: 71,
        protein: 5.7,
        fat: 1.3,
        carbohydrate: 9,
        fiber: 0,
        natrium: 1114,
        cholesterol: 0,
        mufa: 0,
        pufa: 0,
        sfa: 0,
      },
      {
        name: 'Mentega',
        type_id: typeMap.get('dasar') || 3,
        bdd: 100,
        calory: 720,
        protein: 0.6,
        fat: 81,
        carbohydrate: 0.4,
        fiber: 0,
        natrium: 653,
        cholesterol: 0,
        mufa: 0,
        pufa: 0,
        sfa: 0,
      },
      {
        name: 'Ikan Gurame Segar',
        type_id: typeMap.get('utama') || 1,
        bdd: 80,
        calory: 92,
        protein: 20,
        fat: 0.7,
        carbohydrate: 0,
        fiber: 0,
        natrium: 30,
        cholesterol: 86,
        mufa: 4.67,
        pufa: 1.85,
        sfa: 2.03,
      },
      {
        name: 'Udang',
        type_id: typeMap.get('utama') || 1,
        bdd: 68,
        calory: 91,
        protein: 21,
        fat: 0.2,
        carbohydrate: 0.1,
        fiber: 0,
        natrium: 178,
        cholesterol: 170,
        mufa: 0.04,
        pufa: 0.08,
        sfa: 0.06,
      },
      {
        name: 'Cumi-cumi',
        type_id: typeMap.get('utama') || 1,
        bdd: 90,
        calory: 75,
        protein: 16.1,
        fat: 0.7,
        carbohydrate: 0.1,
        fiber: 0,
        natrium: 37,
        cholesterol: 250,
        mufa: 0.03,
        pufa: 0.19,
        sfa: 0.11,
      },
      {
        name: 'Minyak Goreng',
        type_id: typeMap.get('dasar') || 3,
        bdd: 100,
        calory: 884,
        protein: 0,
        fat: 100,
        carbohydrate: 0,
        fiber: 0,
        natrium: 0,
        cholesterol: 0,
        mufa: 36.7,
        pufa: 9.16,
        sfa: 47.08,
      },
      {
        name: 'Ayam',
        type_id: typeMap.get('utama') || 1,
        bdd: 58,
        calory: 298,
        protein: 18.2,
        fat: 25,
        carbohydrate: 0,
        fiber: 0,
        natrium: 109,
        cholesterol: 91.96,
        mufa: 3.67,
        pufa: 1.28,
        sfa: 2.31,
      },
      {
        name: 'Ikan Gurame',
        type_id: typeMap.get('utama') || 1,
        bdd: 80,
        calory: 92,
        protein: 20,
        fat: 0.7,
        carbohydrate: 0,
        fiber: 0,
        natrium: 30,
        cholesterol: 86,
        mufa: 4.7,
        pufa: 1.9,
        sfa: 2,
      },
      {
        name: 'Madu',
        type_id: typeMap.get('pelengkap') || 2,
        bdd: 100,
        calory: 294,
        protein: 0.3,
        fat: 0,
        carbohydrate: 79.5,
        fiber: 0.2,
        natrium: 6,
        cholesterol: 0,
        mufa: 0,
        pufa: 0,
        sfa: 0,
      },
      {
        name: 'Margarine',
        type_id: typeMap.get('dasar') || 3,
        bdd: 100,
        calory: 720,
        protein: 0.6,
        fat: 81,
        carbohydrate: 0.4,
        fiber: 0,
        natrium: 653,
        cholesterol: 5,
        mufa: 39.32,
        pufa: 12.98,
        sfa: 23.04,
      },
      {
        name: 'Ikan Dori',
        type_id: typeMap.get('utama') || 1,
        bdd: 80,
        calory: 132,
        protein: 17,
        fat: 6.6,
        carbohydrate: 1.1,
        fiber: 0,
        natrium: 77,
        cholesterol: 0,
        mufa: 0,
        pufa: 0,
        sfa: 0,
      },
      {
        name: 'Mayonaise',
        type_id: typeMap.get('dasar') || 3,
        bdd: 100,
        calory: 700,
        protein: 0,
        fat: 70,
        carbohydrate: 10,
        fiber: 0,
        natrium: 575,
        cholesterol: 60,
        mufa: 35.68,
        pufa: 27.25,
        sfa: 6.69,
      },
      {
        name: 'Cumi - Cumi Fillet',
        type_id: typeMap.get('utama') || 1,
        bdd: 100,
        calory: 75,
        protein: 16.1,
        fat: 0.7,
        carbohydrate: 0.1,
        fiber: 0,
        natrium: 37,
        cholesterol: 250,
        mufa: 0.03,
        pufa: 0.19,
        sfa: 0.11,
      },
      {
        name: 'Pete',
        type_id: typeMap.get('pelengkap') || 2,
        bdd: 36,
        calory: 142,
        protein: 10.4,
        fat: 2,
        carbohydrate: 22,
        fiber: 2,
        natrium: 55,
        cholesterol: 0,
        mufa: 0,
        pufa: 0,
        sfa: 0,
      },
      {
        name: 'Buntut Sapi',
        type_id: typeMap.get('utama') || 1,
        bdd: 100,
        calory: 210,
        protein: 18.8,
        fat: 14,
        carbohydrate: 0,
        fiber: 0,
        natrium: 105,
        cholesterol: 76,
        mufa: 27.24,
        pufa: 1.3,
        sfa: 13.2,
      },
      {
        name: 'Kentang',
        type_id: typeMap.get('pelengkap') || 2,
        bdd: 100,
        calory: 62,
        protein: 2.1,
        fat: 0.2,
        carbohydrate: 13.5,
        fiber: 0.5,
        natrium: 7,
        cholesterol: 0,
        mufa: 0,
        pufa: 0.02,
        sfa: 0.01,
      },
      {
        name: 'Tomat',
        type_id: typeMap.get('pelengkap') || 2,
        bdd: 100,
        calory: 24,
        protein: 1.3,
        fat: 0.5,
        carbohydrate: 4.7,
        fiber: 0,
        natrium: 0,
        cholesterol: 0,
        mufa: 0.01,
        pufa: 0.03,
        sfa: 0.02,
      },
      {
        name: 'Daun Bawang',
        type_id: typeMap.get('pelengkap') || 2,
        bdd: 100,
        calory: 41,
        protein: 2,
        fat: 0.3,
        carbohydrate: 7.8,
        fiber: 2.1,
        natrium: 0,
        cholesterol: 0,
        mufa: 0.01,
        pufa: 0.08,
        sfa: 0.04,
      },
      {
        name: 'Seledri',
        type_id: typeMap.get('pelengkap') || 2,
        bdd: 63,
        calory: 23,
        protein: 1,
        fat: 0.1,
        carbohydrate: 4.6,
        fiber: 2,
        natrium: 10,
        cholesterol: 0,
        mufa: 0.01,
        pufa: 0.13,
        sfa: 0.06,
      },
      {
        name: 'Bawang Merah Goreng',
        type_id: typeMap.get('pelengkap') || 2,
        bdd: 88,
        calory: 112,
        protein: 4.5,
        fat: 0.2,
        carbohydrate: 23.1,
        fiber: 0.6,
        natrium: 0,
        cholesterol: 0,
        mufa: 3.48,
        pufa: 1.55,
        sfa: 0.42,
      },
    ];

    const masterBumbuData = [
      {
        name: 'Adonan Basah',
        cooking_type: null,
        bdd: 100,
        calory: 162,
        protein: 5,
        fat: 2,
        carbohydrate: 33,
        fiber: 0,
        natrium: 427,
        cholesterol: 0,
        sfa: 0,
        mufa: 0,
        pufa: 0,
      },
      {
        name: 'Kremes',
        cooking_type: null,
        bdd: 100,
        calory: 97.408963911525,
        protein: 0.962724097788126,
        fat: 1.19750873108265,
        carbohydrate: 20.5753958090803,
        fiber: 0.209545983701979,
        natrium: 217.442258440047,
        cholesterol: 0,
        sfa: 0,
        mufa: 0,
        pufa: 0,
      },
      {
        name: 'Bumbu Ungkep Kuning',
        cooking_type: null,
        bdd: 100,
        calory: 12,
        protein: 0,
        fat: 1,
        carbohydrate: 1,
        fiber: 0,
        natrium: 606,
        cholesterol: 0,
        sfa: 0,
        mufa: 0,
        pufa: 0,
      },
      {
        name: 'Marinasi / Marinated',
        cooking_type: null,
        bdd: 100,
        calory: 5,
        protein: 0,
        fat: 0,
        carbohydrate: 1,
        fiber: 1,
        natrium: 857,
        cholesterol: 0,
        sfa: 0,
        mufa: 0,
        pufa: 0,
      },
    ];

    // Upsert MasterBahan
    for (const bahan of masterBahanData) {
      await prismaClient.masterBahan.upsert({
        where: { name: bahan.name },
        update: bahan,
        create: bahan,
      });
    }

    // Upsert MasterBumbu
    for (const bumbu of masterBumbuData) {
      await prismaClient.masterBumbu.upsert({
        where: { name: bumbu.name },
        update: bumbu,
        create: bumbu,
      });
    }

    res.status(200).json({
      message: 'Master Bahan and Master Bumbu seeded/updated successfully',
    });
  } catch (e) {
    next(e);
  }
}
